# .gemini/commands/актуализацияДокументации.toml

name = "Актуализация документации"
description = "Обновляет ключевые файлы документации проекта (GEMINI.md и input/anchor-context.md) для отражения последних выполненных работ и принятых решений."

# Инструкция для Gemini
prompt = '''
После завершения значимого этапа работы, выполни следующие действия для обновления документации:

1.  **Проанализируй выполненную работу:** Какая проблема была решена? Какое ключевое решение было принято?

2.  **Сформулируй запись для `input/anchor-context.md`:**
    *   Создай новую запись в разделе "Журнал работ".
    *   Запись должна быть **очень краткой**.
    *   Укажи **проблему** и **решение** без упоминания конкретных имен файлов или деталей реализации.
    *   Пример:
        ```
        ### ГГГГ-ММ-ДД: Краткое описание
        **Проблема:** Описание проблемы.
        **Решение:** Концептуальное описание решения.
        ```

3.  **Сформулируй обновление для `GEMINI.md`:**
    *   Проверь, нужно ли обновить раздел `## Key Files`, добавив новые созданные файлы или изменив описание существующих.
    *   Проверь, не устарели ли другие разделы, например, `## Architecture`.

4.  **Предложи изменения пользователю:** Покажи пользователю предлагаемые изменения для обоих файлов и дождись его одобрения перед их применением.
'''

# Файлы, к которым применяется команда
files = [
  "GEMINI.md",
  "input/anchor-context.md"
]
