name = "Следующий шаг"
description = "Определение и согласование следующего шага в реализации проекта"

prompt = """
Проанализируй файл `input/anchor-context.md`, особенно разделы "План работ" и "Журнал работ".
Сравни список выполненных задач в журнале с общим планом.
Определи следующий нереализованный приоритет из плана работ.

Затем сформулируй подробный план действий для реализации этого шага. План должен включать в себя список файлов, которые необходимо проанализировать для полного понимания контекста.
Предложи этот план мне на согласование.

Если я соглашусь, приступай к выполнению этого плана, начиная с анализа указанных файлов.
"""

files = [
  "input/anchor-context.md"
]